package com.kcbranding.keycloak.css;

import java.util.function.UnaryOperator;

import com.kcbranding.keycloak.config.BrandingConfig;
import com.kcbranding.keycloak.config.BrandingField;

/**
 * Generates the per-realm stylesheet. It only declares custom properties (plus the admin's custom
 * CSS); the structural rules that consume them live in the theme's static CSS files. All values were
 * validated by {@link com.kcbranding.keycloak.config.BrandingValidator}, so they are safe to inline.
 */
public final class CssGenerator {

    public enum Scope { LOGIN, CONSOLE }

    private CssGenerator() {
    }

    /**
     * @param config      effective configuration
     * @param scope       which UI the stylesheet is for
     * @param urlResolver turns a URL/asset setting into a browser-usable URL
     */
    public static String generate(BrandingConfig config, Scope scope, UnaryOperator<String> urlResolver) {
        String primary = config.get(BrandingField.PRIMARY_COLOR);
        String hover = config.primaryHoverColor();

        StringBuilder css = new StringBuilder(2048);
        css.append("/* Generated by keycloak-configurable-theme, version ").append(config.version()).append(" */\n");
        css.append(":root, :root.pf-v5-theme-dark {\n");
        prop(css, "--cfg-primary", primary);
        prop(css, "--cfg-primary-hover", hover);
        prop(css, "--cfg-accent", config.getOr(BrandingField.ACCENT_COLOR, BrandingField.PRIMARY_COLOR));
        prop(css, "--cfg-link", config.getOr(BrandingField.LINK_COLOR, BrandingField.PRIMARY_COLOR));
        prop(css, "--cfg-bg", config.get(BrandingField.BACKGROUND_COLOR));
        prop(css, "--cfg-header-text", config.get(BrandingField.HEADER_TEXT_COLOR));
        prop(css, "--cfg-hero-bg", config.getOr(BrandingField.HERO_BACKGROUND_COLOR, BrandingField.PRIMARY_COLOR));
        prop(css, "--cfg-radius", config.get(BrandingField.BORDER_RADIUS));
        prop(css, "--cfg-card-width", config.get(BrandingField.CARD_WIDTH));
        prop(css, "--cfg-logo-height", config.get(BrandingField.LOGO_HEIGHT));
        if (config.has(BrandingField.BACKGROUND_OVERLAY)) {
            prop(css, "--cfg-bg-overlay", config.get(BrandingField.BACKGROUND_OVERLAY));
        }
        if (config.has(BrandingField.BACKGROUND_IMAGE_URL)) {
            prop(css, "--cfg-bg-image", cssUrl(urlResolver.apply(config.get(BrandingField.BACKGROUND_IMAGE_URL))));
        }
        if (config.has(BrandingField.LOGO_URL)) {
            prop(css, "--cfg-logo-url", cssUrl(urlResolver.apply(config.get(BrandingField.LOGO_URL))));
        }
        if (config.has(BrandingField.LOGO_DARK_URL)) {
            prop(css, "--cfg-logo-dark-url", cssUrl(urlResolver.apply(config.get(BrandingField.LOGO_DARK_URL))));
        }
        if (config.has(BrandingField.LOGO_DARK_URL) || config.has(BrandingField.LOGO_URL)) {
            String consoleLogo = config.getOr(BrandingField.LOGO_DARK_URL, BrandingField.LOGO_URL);
            prop(css, "--cfg-console-logo-url", cssUrl(urlResolver.apply(consoleLogo)));
        }
        if (config.has(BrandingField.CONSOLE_HEADER_COLOR)) {
            prop(css, "--cfg-console-header", config.get(BrandingField.CONSOLE_HEADER_COLOR));
        }

        // PatternFly 5 tokens used by the login pages and both consoles.
        prop(css, "--pf-v5-global--primary-color--100", "var(--cfg-primary)");
        prop(css, "--pf-v5-global--primary-color--200", "var(--cfg-primary-hover)");
        prop(css, "--pf-v5-global--link--Color", "var(--cfg-link)");
        prop(css, "--pf-v5-global--link--Color--hover", "var(--cfg-primary-hover)");
        prop(css, "--pf-v5-global--BorderRadius--sm", "var(--cfg-radius)");
        prop(css, "--pf-v5-global--active-color--100", "var(--cfg-primary)");
        prop(css, "--keycloak-card-top-color", "var(--cfg-accent)");
        if (config.has(BrandingField.FONT_FAMILY)) {
            String font = config.get(BrandingField.FONT_FAMILY);
            prop(css, "--pf-v5-global--FontFamily--text", font);
            prop(css, "--pf-v5-global--FontFamily--heading", font);
            prop(css, "--pf-v5-global--FontFamily--sans-serif", font);
            prop(css, "--pf-v5-global--FontFamily--redhat-updated--sans-serif", font);
            prop(css, "--pf-v5-global--FontFamily--redhat-updated--heading--sans-serif", font);
        }
        css.append("}\n");

        // Light-mode-only surfaces; dark mode keeps PatternFly's dark palette for readability.
        css.append(":root:not(.pf-v5-theme-dark) {\n");
        prop(css, "--cfg-card-bg", config.get(BrandingField.CARD_BACKGROUND_COLOR));
        prop(css, "--cfg-text", config.get(BrandingField.TEXT_COLOR));
        css.append("}\n");

        if (scope == Scope.LOGIN && config.has(BrandingField.FONT_FAMILY)) {
            css.append("body, .pf-v5-c-login { font-family: var(--pf-v5-global--FontFamily--text); }\n");
        }
        if (config.has(BrandingField.CUSTOM_CSS)) {
            css.append("\n/* Custom CSS */\n").append(config.get(BrandingField.CUSTOM_CSS)).append('\n');
        }
        return css.toString();
    }

    private static void prop(StringBuilder css, String name, String value) {
        css.append("  ").append(name).append(": ").append(value).append(";\n");
    }

    /** Validated URLs never contain quotes, backslashes or whitespace, so double quoting is enough. */
    static String cssUrl(String url) {
        return "url(\"" + url.replace("\"", "%22").replace("\\", "%5C") + "\")";
    }
}
